### DISCUSSION TITLE
Possible issue when detecting cheapest hours

### DISCUSSION THREAD

**Discussion by mtrekker** [kotope/aio_energy_management#45] [Q&A]
I am not sure why the cheapest hours is not honoring the `first_hour` (22.00) setting and scheduled to start at 21.00. I have set up this limit because of energy tariffs cut over is happening at 22.00. It should honor this setting, shouldn't it ?

update.aio_energy_management_update:
```
auto_update: false
display_precision: 0
installed_version: 0.3.2
in_progress: false
latest_version: 0.3.2
release_summary: null
release_url: https://github.com/kotope/aio_energy_management/releases/0.3.2
skipped_version: null
title: null
update_percentage: null
entity_picture: https://brands.home-assistant.io/_/aio_energy_management/icon.png
friendly_name: AIO Energy Management update
supported_features: 23
```

configuration.yaml:
```
aio_energy_management:
  cheapest_hours:
    - nordpool_entity: sensor.nordpool_kwh_xx_eur_x_xxx_xxx
      unique_id: nordpool_cheapest_hours_sensor
      name: Cheapest Hours
      first_hour: 22
      last_hour: 12
      starting_today: true
      number_of_hours: 4
      sequential: False
      failsafe_starting_hour: 22
    - nordpool_entity: sensor.nordpool_kwh_xx_eur_x_xxx_xxx
      unique_id: nordpool_expensive_hours_sensor
      name: Expensive Hours
      first_hour: 20
      last_hour: 16
      starting_today: true
      number_of_hours: 2
      sequential: False
      inversed: true
  calendar:
    name: Nordpool Energy Management Calendar
    unique_id: nordpool_energy_management_calendar
```

calendar.nordpool_energy_management_calendar:
```
message: Cheapest Hours
all_day: false
start_time: "2024-12-05 21:00:00"
end_time: "2024-12-06 01:00:00"
location: ""
description: ""
friendly_name: Nordpool Energy Management Calendar
```

Nordpool sensor data:
```
tomorrow_valid: true
raw_today:
  - start: "2024-12-05T00:00:00+02:00"
    end: "2024-12-05T01:00:00+02:00"
    value: 3.195
  - start: "2024-12-05T01:00:00+02:00"
    end: "2024-12-05T02:00:00+02:00"
    value: 5.49
  - start: "2024-12-05T02:00:00+02:00"
    end: "2024-12-05T03:00:00+02:00"
    value: 2.989
  - start: "2024-12-05T03:00:00+02:00"
    end: "2024-12-05T04:00:00+02:00"
    value: 0.781
  - start: "2024-12-05T04:00:00+02:00"
    end: "2024-12-05T05:00:00+02:00"
    value: 0.6
  - start: "2024-12-05T05:00:00+02:00"
    end: "2024-12-05T06:00:00+02:00"
    value: 0.78
  - start: "2024-12-05T06:00:00+02:00"
    end: "2024-12-05T07:00:00+02:00"
    value: 5.355
  - start: "2024-12-05T07:00:00+02:00"
    end: "2024-12-05T08:00:00+02:00"
    value: 10.133
  - start: "2024-12-05T08:00:00+02:00"
    end: "2024-12-05T09:00:00+02:00"
    value: 14.339
  - start: "2024-12-05T09:00:00+02:00"
    end: "2024-12-05T10:00:00+02:00"
    value: 15.249
  - start: "2024-12-05T10:00:00+02:00"
    end: "2024-12-05T11:00:00+02:00"
    value: 12.969
  - start: "2024-12-05T11:00:00+02:00"
    end: "2024-12-05T12:00:00+02:00"
    value: 11.917
  - start: "2024-12-05T12:00:00+02:00"
    end: "2024-12-05T13:00:00+02:00"
    value: 10.386
  - start: "2024-12-05T13:00:00+02:00"
    end: "2024-12-05T14:00:00+02:00"
    value: 10.271
  - start: "2024-12-05T14:00:00+02:00"
    end: "2024-12-05T15:00:00+02:00"
    value: 10.271
  - start: "2024-12-05T15:00:00+02:00"
    end: "2024-12-05T16:00:00+02:00"
    value: 10.271
  - start: "2024-12-05T16:00:00+02:00"
    end: "2024-12-05T17:00:00+02:00"
    value: 10.272
  - start: "2024-12-05T17:00:00+02:00"
    end: "2024-12-05T18:00:00+02:00"
    value: 10.271
  - start: "2024-12-05T18:00:00+02:00"
    end: "2024-12-05T19:00:00+02:00"
    value: 10.271
  - start: "2024-12-05T19:00:00+02:00"
    end: "2024-12-05T20:00:00+02:00"
    value: 10.271
  - start: "2024-12-05T20:00:00+02:00"
    end: "2024-12-05T21:00:00+02:00"
    value: 3.764
  - start: "2024-12-05T21:00:00+02:00"
    end: "2024-12-05T22:00:00+02:00"
    value: 1.575
  - start: "2024-12-05T22:00:00+02:00"
    end: "2024-12-05T23:00:00+02:00"
    value: 1.562
  - start: "2024-12-05T23:00:00+02:00"
    end: "2024-12-06T00:00:00+02:00"
    value: 3.048
raw_tomorrow:
  - start: "2024-12-06T00:00:00+02:00"
    end: "2024-12-06T01:00:00+02:00"
    value: 1.767
  - start: "2024-12-06T01:00:00+02:00"
    end: "2024-12-06T02:00:00+02:00"
    value: 7
  - start: "2024-12-06T02:00:00+02:00"
    end: "2024-12-06T03:00:00+02:00"
    value: 6.45
  - start: "2024-12-06T03:00:00+02:00"
    end: "2024-12-06T04:00:00+02:00"
    value: 5.949
  - start: "2024-12-06T04:00:00+02:00"
    end: "2024-12-06T05:00:00+02:00"
    value: 5.794
  - start: "2024-12-06T05:00:00+02:00"
    end: "2024-12-06T06:00:00+02:00"
    value: 6.144
  - start: "2024-12-06T06:00:00+02:00"
    end: "2024-12-06T07:00:00+02:00"
    value: 6.71
  - start: "2024-12-06T07:00:00+02:00"
    end: "2024-12-06T08:00:00+02:00"
    value: 11.468
  - start: "2024-12-06T08:00:00+02:00"
    end: "2024-12-06T09:00:00+02:00"
    value: 13.908
  - start: "2024-12-06T09:00:00+02:00"
    end: "2024-12-06T10:00:00+02:00"
    value: 15.833
  - start: "2024-12-06T10:00:00+02:00"
    end: "2024-12-06T11:00:00+02:00"
    value: 12.932
  - start: "2024-12-06T11:00:00+02:00"
    end: "2024-12-06T12:00:00+02:00"
    value: 15.344
  - start: "2024-12-06T12:00:00+02:00"
    end: "2024-12-06T13:00:00+02:00"
    value: 10.38
  - start: "2024-12-06T13:00:00+02:00"
    end: "2024-12-06T14:00:00+02:00"
    value: 11.004
  - start: "2024-12-06T14:00:00+02:00"
    end: "2024-12-06T15:00:00+02:00"
    value: 15.257
  - start: "2024-12-06T15:00:00+02:00"
    end: "2024-12-06T16:00:00+02:00"
    value: 12.728
  - start: "2024-12-06T16:00:00+02:00"
    end: "2024-12-06T17:00:00+02:00"
    value: 20.467
  - start: "2024-12-06T17:00:00+02:00"
    end: "2024-12-06T18:00:00+02:00"
    value: 13.12
  - start: "2024-12-06T18:00:00+02:00"
    end: "2024-12-06T19:00:00+02:00"
    value: 15.311
  - start: "2024-12-06T19:00:00+02:00"
    end: "2024-12-06T20:00:00+02:00"
    value: 15.638
  - start: "2024-12-06T20:00:00+02:00"
    end: "2024-12-06T21:00:00+02:00"
    value: 20.056
  - start: "2024-12-06T21:00:00+02:00"
    end: "2024-12-06T22:00:00+02:00"
    value: 10.224
  - start: "2024-12-06T22:00:00+02:00"
    end: "2024-12-06T23:00:00+02:00"
    value: 10.224
  - start: "2024-12-06T23:00:00+02:00"
    end: "2024-12-07T00:00:00+02:00"
    value: 10.047
```
