### DISCUSSION TITLE
Adding event when recalculation is done

### DISCUSSION THREAD

**Discussion by ThermIQ** [kotope/aio_energy_management#52] [Ideas]
It would be great to have an event once AIO has done a recalculation of hours. Could be used to update a graphical representation of cheapest hours/hours blocked

**Comment by kotope** [comment]
This can be already done, just make trigger to listen updated_at attribute.
Once recalculation is done, updated_at attribute will be updated :-)

**Reply by ThermIQ** [reply]
Like this?  

`- trigger: state`
`  entity_id: my_cheapest_hours.updated_at`

**Reply by kotope** [reply]
You need to trigger on attribute, like this:

```
  - trigger: state
    entity_id:
      - binary_sensor.my_cheapest_hours
    attribute: updated_at

```
