### DISCUSSION TITLE
[SOLVED] ERROR: Invalid configuration for non-sequential cheapest hours sensor

### DISCUSSION THREAD

**Discussion by typxxi** [kotope/aio_energy_management#58] [General]
Error message in my log file 

![image](https://github.com/user-attachments/assets/53053e06-46f8-415c-a2a2-21c73839065a)

I have set the number of hours in my configuration yaml to 'input_number.aio_tibbers_gunstigste_stunden_anzahl' which is set to 3

I tried with the most expensive hours and set the number manually to 2

Here is my yaml configuration
```
aio_energy_management:
  cheapest_hours:
    - nordpool_entity: sensor.nordpool_kwh_ger_eur_4_10_0
      unique_id: aio_tibbers_cheapest_hours_today
      name: TIBBERS BESTE STUNDEN - HEUT [AIO]
      first_hour: 13
      last_hour: 23
      starting_today: true
      number_of_hours: input_number.aio_tibbers_gunstigste_stunden_anzahl
      sequential: false
      failsafe_starting_hour: 20
      # trigger_time: 17:30
      # max_price: 25.5

    - nordpool_entity: sensor.nordpool_kwh_ger_eur_4_10_0
      unique_id: aio_tibbers_cheapest_hours_tomorrow
      name: TIBBERS BESTE STUNDEN - MORGEN [AIO]
      first_hour: 1
      last_hour: 23
      starting_today: false
      number_of_hours: input_number.aio_tibbers_gunstigste_stunden_anzahl
      sequential: False
      failsafe_starting_hour: 20
      # trigger_time: 17:30
      # max_price: 25.5

    - nordpool_entity: sensor.nordpool_kwh_ger_eur_4_10_0
      unique_id: aio_tibbers_expensive_hours
      name: TIBBERS TEUERSTE STUNDEN [AIO]
      first_hour: 18
      last_hour: 20
      starting_today: false
      number_of_hours: 2
      sequential: False
      failsafe_starting_hour: 18
      inversed: true
      # trigger_time: 18:30
      # max_price: 40.0

  calendar:
    name: AIO STROMPREISE
    unique_id: aio_tibber_energy_management_calendar
```

Thanks a lot
