### DISCUSSION TITLE
Adding the ability to control how cheapest or most expensive hours get selected

### DISCUSSION THREAD

**Discussion by mtchetch** [kotope/aio_energy_management#68] [Ideas]
I've been using this tool for my energy-saving automations for a while now. While its basic approach of selecting the cheapest or most expensive hours works well, I've found that it can be too simplistic for real-world scenarios. In my setup, I enhance the process by:

-  Measuring the Daily Delta: I calculate the difference in energy prices (delta) from Nord Pool. If the delta is below a certain threshold, I skip energy-saving actions—even if the hours are technically the most expensive or cheapest.

- Example: If I plan to save energy during the six most expensive hours but find that the price difference is only 2 snt/kWh, it doesn’t justify turning off the heating.

- Handling Short Peaks: Sometimes, there are short periods of significantly higher prices that don’t last long enough to meet my preset window.

- Example: If the automation is triggered for a 6-hour window based on a delta threshold of 6 snt/kWh, but only 3 hours reach 20 snt/kWh while the remaining hours only have a 3 snt/kWh delta, the automation ends up turning devices off during those less significant periods as well.

-  Managing Longer Peaks: On the other hand, prolonged periods of high prices can also pose a challenge. A longer peak may include several consecutive hours where the price remains elevated, yet not every hour might meet the strict delta criteria. For these cases, the automation should be capable of distinguishing between sustained high delta periods and temporary fluctuations. Incorporating logic that considers both the intensity and duration of these price peaks would allow the automation to trigger energy-saving measures only when the elevated prices are both significant and prolonged, thus avoiding unnecessary actions during marginally elevated periods.

To address these issues, I propose adding more configuration options that would allow users to:

- Control and Measure Delta Values: Introduce additional sensors or parameters that update hourly, reflecting the actual price differences.

- Refine Hour Selection: Modify the selection algorithm for expensive or cheapest hours so that it ignores hours where the delta does not meet the user-defined threshold.

Energy saving is important when the price is 20snt/kwh but not so much when it is 4. 

I have a few cards defined that visualize this and I suppose that these should probably be included so that it is easier to understand what is happening and how the expensive or cheap hours are generated in realtion with energy pricing.

These enhancements would make the automation more dynamic and better aligned with actual energy-saving opportunities.

![image](https://github.com/user-attachments/assets/8253f1ee-b665-41e6-b60d-af2f9ca9f537)

![image](https://github.com/user-attachments/assets/237e2560-3f6a-4dd6-a9bf-7f747eb79725)

![image](https://github.com/user-attachments/assets/4ae70133-50f1-4770-8cda-205403434c66)

```
type: custom:apexcharts-card
header:
  show: true
  title: nordpool vs expensive hours
  colorize_states: true
graph_span: 96h
series:
  - entity: binary_sensor.expensive_hours
    name: Expensive Hours
    type: area
    yaxis_id: second
    curve: stepline
    color: "#ff0000"
    transform: "return x === \"on\" ? 0.3 : 0;"
    stroke_width: 1
  - entity: sensor.nordpool_kwh_fi_eur_3_10_024
    name: nordpool
    type: line
    stroke_width: 3
    curve: stepline
    yaxis_id: first
yaxis:
  - id: first
    decimals: 3
    opposite: false
  - id: second
    opposite: true
    show: false
  - id: third
    opposite: true
    show: true

```

```
type: custom:apexcharts-card
header:
  show: true
  title: expensive hours vs energy usage
  colorize_states: true
graph_span: 96h
series:
  - entity: binary_sensor.expensive_hours
    name: Expensive Hours
    type: area
    yaxis_id: second
    curve: stepline
    color: "#ff0000"
    transform: "return x === \"on\" ? 0.3 : 0;"
    stroke_width: 1
  - entity: sensor.low_res_power_usage_watts
    name: energy usage
    type: line
    stroke_width: 2
    curve: stepline
    yaxis_id: first
    group_by:
      duration: 30min
      func: avg
yaxis:
  - id: first
    decimals: 3
    opposite: false
  - id: second
    opposite: true
    show: false
  - id: third
    opposite: true
    show: true

```
