### DISCUSSION TITLE
Invalid configuration for non-sequential cheapest hours sensor

### DISCUSSION THREAD

**Discussion by mtrekker** [kotope/aio_energy_management#77] [Q&A]
I can't figure it out why the following configuration is generating this error. My goal is to operate cheapest hours within 22.00 - 07.00.

```
2025-05-12 18:07:26.509 ERROR (MainThread) [custom_components.aio_energy_management.math] Invalid configuration for non-sequential cheapest hours sensor
```
[configuration.yaml]
```
aio_energy_management:
    cheapest_hours:
      - nordpool_entity: sensor.nordpool
        unique_id: my_cheapest_hours
        name: My Cheapest Hours
        first_hour: 22
        last_hour: 6
        starting_today: true
        number_of_hours: 2
        sequential: false
      - nordpool_entity: sensor.nordpool
        unique_id: my_expensive_hours
        name: Expensive Hours
        first_hour: 0
        last_hour: 23
        starting_today: false
        number_of_hours: 2
        sequential: false
        inversed: true
  calendar:
    name: Energy Management
    unique_id: energy_management_calendar
```
