### DISCUSSION TITLE
Unable to add second timeslot for cheap hours at night

### DISCUSSION THREAD

**Discussion by Alwik** [kotope/aio_energy_management#80] [Q&A] [answered]
Hi!
I have started using this great tool a couple of days ago, and am super happy with it for controlling my hot water heat pump. Now I'm also trying to add car-charging at night. The idea is that if I plug in my car in the evening, I want it to charge at the lowest rate at night. For this I have added a second configuration-block in the configuration. Unfortunately only the first one works (I can see the calendar-event, and the DHW turns on), but for the second one I don't get the calendar event, and the second switch doesn't work either. Can someone see what I'm doing wrong?
```
aio_energy_management:
    cheapest_hours:
      - entsoe_entity: sensor.average_electricity_price
        unique_id: my_cheapest_hours
        name: My Cheapest Hours
        first_hour: 0
        last_hour: 23
        starting_today: false
        number_of_hours: 5
        sequential: false
        failsafe_starting_hour: 10
        calendar: true
      - entsoe_entity: sensor.average_electricity_price
        unique_id: my_cheapest_hours_at_night
        name: My Cheapest Hours at Night
        first_hour: 20
        last_hour: 07
        starting_today: false
        number_of_hours: 5
        sequential: false
        failsafe_starting_hour: 0
        calendar: true
    calendar:
      name: Energy Management
      unique_id: energy_management_calendar
```
