### ISSUE TITLE
Feature request - set max hour price

### ISSUE THREAD

**Issue by emalihin** [kotope/aio_energy_management#15]
Thank you for this excellent component! Would you consider adding a new optional field to cap the cheapest hours at a defined max price? This would allow creating additional "optional" sensors which would only turn on if hours with a price below `max_price` are found? E.g.:

```
      - nordpool_entity: sensor.nordpool
        unique_id: my_cheapest_hours_mandatory
        name: My Cheapest Hours - Mandatory consumers
        first_hour: 21
        last_hour: 12
        starting_today: true
        number_of_hours: 3
        sequential: false
        failsafe_starting_hour: 1

      - nordpool_entity: sensor.nordpool
        unique_id: my_cheapest_hours_optional
        name: My Cheapest Hours - Optional consumers
        first_hour: 21
        last_hour: 12
        max_price: 0.099 <<< new field
        starting_today: true
        number_of_hours: 3
        sequential: false
        failsafe_starting_hour: 1
```

**Comment by kotope** [comment]
Yes, this has been requested previously also on other channels and is definitely on my TODO list next on the line. :-)

**Comment by kotope** [comment]
Merged to dev branch. Will be released on 0.3.0 later this week.

**Comment by emalihin** [comment]
Great news, thank you @kotope ! Follow up question (maybe a feature request) - with this new feature added, how do I set up the entity such that it will turn the sensor on for every hour where the price is below `max_price`? Doesn't need to be sequential, but needs to turn on every hour below `max_price`?

**Comment by kotope** [comment]
max_price is now published with 0.3.0

**Comment by emalihin** [comment]
Thank you! Trying with this config now to fill every hour below 0.03 cents/kWh:

```
aio_energy_management:
    cheapest_hours:
      - nordpool_entity: sensor.nordpool
        unique_id: my_cheapest_hours
        name: My Cheapest Hours
        first_hour: 0
        last_hour: 23
        starting_today: True
        number_of_hours: 24
        max_price: 0.03
        sequential: false
        failsafe_starting_hour: 0
    calendar:
        name: Energy Management
        unique_id: energy_management_calendar
```
