### ISSUE TITLE
Feature Request: Delay off by X hours

### ISSUE THREAD

**Issue by chacques** [kotope/aio_energy_management#44]
Use case: I am using cheapest hours to control relay for water boiler. Typically full heating will take ~2.5 hours, but sometimes in worst case it could be 5 or even 6 hours.

Problem is that currently one has to search for 6 hour window for cheapest hours to make sure water gets warm each time. In practise this means that first hour(s) could still be expensive for that long period.

Possible solution:
Would it be possible to add "delay_off_by_n_hours" or something similar parameter? I mean, then it would be possible to search for cheapest 2 or 3 hours, but off-event will be fired delayed by "delay_off_by_n_hours" hours (just to be safe if hot water was consumed a lot on previous day).

That would be more optimal solution energy usage wise.

**Comment by kotope** [comment]
Interesting approach and could be a solution if the typical use of hot water is about 50% and could work when using sequential hours. On non-sequantial configuration, might not work as there might be very high electricity prices between cheap ones. On non-sequential configuration it could hit those easily.

I'll take this into consideration if it's worth implementing. Should be a easy task though.

Not exactly related to feature suggestion itself, but for more accurate results I'd suggest building some kind of measurement system for the hot water tank and then using trigger_hour and dynamic number_of_hours variable. 

Example:
Every evening at 21:00 your automation checks the hot water capacity. If it's half full, you need 3 hours to warm the water. Your automation sets the input_number to 3 for AIO Energy Management and trigger time to 21:00. After the check the aio energy management will find you three hours for upcoming night.
If your hot water tank is near empty, just set the input number to 6.

That way you get exact amount of cheapest hours to use :-)

I'm currently prototyping such a system will write a blog post of it still during end of the year.
As a sneak peak, I'm using ESP32 + three DS8120 sensors outside the tank on different levels of tank to see if I have 0%, 50% or 100% warm water left. 
Not a perfect solution, but so far it seems to give good enough results. :-)

**Comment by jeto** [comment]
You can just use the delay action in automation to delay the off event.
Copying the example from kotope's blog and just add delay before the off action.
```
alias: Cheapest hours turn on switch
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.my_cheapest_hours
    from: "off"
    to: "on"
    id: turn_on
  - platform: state
    entity_id:
      - binary_sensor.my_cheapest_hours
    from: "on"
    to: "off"
    id: turn_off
condition: []
action:
  - if:
      - condition: trigger
        id:
          - turn_on
    then:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.test_toggle
    else:
      - delay:
          hours: 2
          minutes: 0
          seconds: 0
          milliseconds: 0
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.test_toggle
mode: single
```
