### ISSUE TITLE
Entso-e - cheapest hours for today duplicated for tomorrow

### ISSUE THREAD

**Issue by xoferz** [kotope/aio_energy_management#64]
I stumbled upon a moment where the prices for tomorrow (20/02) are not yet available, but somehow the cheapest hours are. At the moment it is 00:30 19/02/2025 EET (GMT+2). The furthest price available is 2025-02-20 00:00:00+02:00 due to Nordpool publishing it in +01:00, but there are calendar entries past that seemingly duplicating today's.

Calendar:

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/59552036-9895-4e2c-8d0c-9fc049ffe90d" />

Relevant configuration:

```
  cheapest_hours:
    - entsoe_entity: sensor.average_electricity_price_today
      unique_id: entso_cheapest_2h_nonconsecutive
      name: "Cheapest 2h non-consecutive"
      first_hour: 0
      last_hour: 22
      starting_today: false
      number_of_hours: 2
      sequential: False
      failsafe_starting_hour: 1  
```

sensor.average_electricity_price_today attributes:
```
state_class: measurement
prices_today:
  - time: "2025-02-19 00:00:00+02:00"
    price: 0.17392
  - time: "2025-02-19 01:00:00+02:00"
    price: 0.1636
  - time: "2025-02-19 02:00:00+02:00"
    price: 0.15958
  - time: "2025-02-19 03:00:00+02:00"
    price: 0.16
  - time: "2025-02-19 04:00:00+02:00"
    price: 0.16091
  - time: "2025-02-19 05:00:00+02:00"
    price: 0.23315
  - time: "2025-02-19 06:00:00+02:00"
    price: 0.19625
  - time: "2025-02-19 07:00:00+02:00"
    price: 0.28882
  - time: "2025-02-19 08:00:00+02:00"
    price: 0.40233
  - time: "2025-02-19 09:00:00+02:00"
    price: 0.40234
  - time: "2025-02-19 10:00:00+02:00"
    price: 0.27749
  - time: "2025-02-19 11:00:00+02:00"
    price: 0.27744
  - time: "2025-02-19 12:00:00+02:00"
    price: 0.22403
  - time: "2025-02-19 13:00:00+02:00"
    price: 0.24245
  - time: "2025-02-19 14:00:00+02:00"
    price: 0.27742
  - time: "2025-02-19 15:00:00+02:00"
    price: 0.27748
  - time: "2025-02-19 16:00:00+02:00"
    price: 0.31385
  - time: "2025-02-19 17:00:00+02:00"
    price: 0.32131
  - time: "2025-02-19 18:00:00+02:00"
    price: 0.40232
  - time: "2025-02-19 19:00:00+02:00"
    price: 0.31952
  - time: "2025-02-19 20:00:00+02:00"
    price: 0.30593
  - time: "2025-02-19 21:00:00+02:00"
    price: 0.28993
  - time: "2025-02-19 22:00:00+02:00"
    price: 0.25808
  - time: "2025-02-19 23:00:00+02:00"
    price: 0.21692
prices_tomorrow:
  - time: "2025-02-20 00:00:00+02:00"
    price: 0.15396
prices:
  - time: "2025-02-19 00:00:00+02:00"
    price: 0.17392
  - time: "2025-02-19 01:00:00+02:00"
    price: 0.1636
  - time: "2025-02-19 02:00:00+02:00"
    price: 0.15958
  - time: "2025-02-19 03:00:00+02:00"
    price: 0.16
  - time: "2025-02-19 04:00:00+02:00"
    price: 0.16091
  - time: "2025-02-19 05:00:00+02:00"
    price: 0.23315
  - time: "2025-02-19 06:00:00+02:00"
    price: 0.19625
  - time: "2025-02-19 07:00:00+02:00"
    price: 0.28882
  - time: "2025-02-19 08:00:00+02:00"
    price: 0.40233
  - time: "2025-02-19 09:00:00+02:00"
    price: 0.40234
  - time: "2025-02-19 10:00:00+02:00"
    price: 0.27749
  - time: "2025-02-19 11:00:00+02:00"
    price: 0.27744
  - time: "2025-02-19 12:00:00+02:00"
    price: 0.22403
  - time: "2025-02-19 13:00:00+02:00"
    price: 0.24245
  - time: "2025-02-19 14:00:00+02:00"
    price: 0.27742
  - time: "2025-02-19 15:00:00+02:00"
    price: 0.27748
  - time: "2025-02-19 16:00:00+02:00"
    price: 0.31385
  - time: "2025-02-19 17:00:00+02:00"
    price: 0.32131
  - time: "2025-02-19 18:00:00+02:00"
    price: 0.40232
  - time: "2025-02-19 19:00:00+02:00"
    price: 0.31952
  - time: "2025-02-19 20:00:00+02:00"
    price: 0.30593
  - time: "2025-02-19 21:00:00+02:00"
    price: 0.28993
  - time: "2025-02-19 22:00:00+02:00"
    price: 0.25808
  - time: "2025-02-19 23:00:00+02:00"
    price: 0.21692
  - time: "2025-02-20 00:00:00+02:00"
    price: 0.15396
unit_of_measurement: €/kWh
attribution: Data provided by ENTSO-e Transparency Platform
icon: mdi:currency-eur
friendly_name: Average electricity price
```
